/**
 * Copies bundled PDFs into public/docs/ and generates src/data/bundledDocs.ts.
 *
 * Two tiers:
 *   docs-bundled/  — committed, always shipped (TMAC itinerary, packing list)
 *   docs-private/  — gitignored, only included when run with --private
 *
 * The invoice lives in docs-private/ because it contains bank account, IBAN and
 * SWIFT details. `npm run build` leaves it out entirely; `npm run build:private`
 * includes it for a build that is only ever served somewhere private.
 */
import { readdirSync, mkdirSync, copyFileSync, writeFileSync, statSync, rmSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const includePrivate = process.argv.includes('--private');
const outDir = join(root, 'public', 'docs');

const TIERS = [
  { dir: 'docs-bundled', private: false },
  ...(includePrivate ? [{ dir: 'docs-private', private: true }] : []),
];

/** Human-friendly titles, keyed by filename. Anything else falls back to the filename. */
const TITLES = {
  'safari-itinerary.pdf': {
    name: 'Final Itinerary — Ryan x 6',
    description: 'The full TMAC booking document: every night, transfer, charter flight and inclusion.',
  },
  'tmac-recommended-packing-list.pdf': {
    name: 'TMAC Recommended Packing List',
    description: "The operator's own packing guidance — luggage rules, clothing, first aid and laundry notes.",
  },
  'tmac-invoice-08099-tim-and-sally-ryan.pdf': {
    name: 'TMAC Invoice 08099 — Tim & Sally Ryan',
    description: 'Balance payment invoice for the party, including bank remittance details.',
  },
};

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const entries = [];
for (const tier of TIERS) {
  const dir = join(root, tier.dir);
  if (!existsSync(dir)) continue;
  for (const file of readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.pdf')).sort()) {
    copyFileSync(join(dir, file), join(outDir, file));
    const meta = TITLES[file] ?? { name: file, description: '' };
    entries.push({
      id: `bundled:${file}`,
      file,
      name: meta.name,
      description: meta.description,
      size: statSync(join(dir, file)).size,
      private: tier.private,
    });
  }
}

const banner = `// GENERATED by scripts/build-docs.mjs — do not edit by hand.\n// Run \`npm run build\` (public docs) or \`npm run build:private\` (adds docs-private/).\n`;
const body = `export interface BundledDoc {
  id: string;
  file: string;
  name: string;
  description: string;
  size: number;
  private: boolean;
}

export const BUNDLED_DOCS: BundledDoc[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(join(root, 'src', 'data', 'bundledDocs.ts'), banner + '\n' + body);

console.log(
  `build-docs: ${entries.length} document(s) -> public/docs/` +
    (includePrivate ? ' (including docs-private/)' : ' (public only, docs-private/ excluded)')
);
for (const e of entries) console.log(`  - ${e.file}${e.private ? '  [private]' : ''}`);
